on: push
name: Quality Gate
jobs:
  compile-and-test:
    name: Compile and test
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.16'

      - name: Run tests
        run: go test -coverprofile=coverage.out ./...

      - name: Set project version in sonar-project.properties
        run: |
          VERSION=$(grep 'VERSION=' Dockerfile | awk -F '=' '{ print $2 }')
          sed -i "s/{{ VERSION }}/$VERSION/g" sonar-project.properties

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
